/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 /Users/gonzalo/Downloads/PizzaOptimizada2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/PizzaOptimizada2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pizza.geometry} material={materials.pizza} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/PizzaOptimizada2.glb')
