/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/public/models/PizzaOptimizada2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pizza.geometry}
        material={materials.pizza}
        scale={0.025}
        /* rotate={0.025} */
      />
    </group>
  );
}

useGLTF.preload("/PizzaOptimizada2.glb");
