/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from "@react-three/drei";
import { IModel } from "../../utils/types";

type Props = {
  model: IModel
}

let preload= ""

export function Model({model}: Props) {
  const uriFile = `/models/${model.archivo}`
  const { nodes, materials } = useGLTF(uriFile);
  preload = model.precarga

  console.log("Hola")

  return (
    <group dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes[model.geometria].geometry}
        material={materials[model.material]}
        scale={1}
      />
    </group>
  );
}

useGLTF.preload(preload);